#!/bin/bash
# Copyright (C) 2023 by Henry Kroll III, www.thenerdshow.com
#
# This is free software.  You may redistribute it under the terms
# of the Apache license and the GNU General Public License Version
# 2 or at your option any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public
# License along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#

# fifo queue to hold temporary audio file names
audio_fifo=$(mktemp); rm "$audio_fifo" ; mkfifo "$audio_fifo"

## create a trap to remove temp files on untimely exit
cleanup() {
    rm -f /tmp/tmp.txt "$audio_fifo"
}
trap cleanup 0

# function to process audio files from queue
trans(){
    while read audio; do
        # transcribe audio
        whisper "$audio" --language English --model small --output_dir /tmp
        # remove temporary audio file
        rm -f "$audio"
        # Type text to terminal, in background
        # Thanks for watching! seems to happen due to noise.
        if [[ $(</tmp/tmp.txt) != "Thanks for watching!" ]]; then
            xdotool type --clearmodifiers --file /tmp/tmp.txt
            xdotool key space
            rm -f /tmp/tmp.txt
        fi &
    done < "$audio_fifo"
    #cleanup
    rm -f "$audio_fifo"
}

# record audio in background
while true; do
    # Make temporary files to hold audio
    tmp=$(mktemp)

    # Listen to mic. The `&` lets it operate in the background.
    # The `1 0.2 3%` part of the sox rec command trims 1 segment of silence from
    # the beginning longer than 0.2 seconds and longer than 3% of the volume level.
    # The final `1 2.0 1%` part tells it to trim 1 segment of silence from the end.
    # It stops recording after 2.0 seconds of silence. Change to 5% or more with
    # poor recording equipment and noisy environments.

    rec -c 1 -r 22050 -t mp3 "$tmp" silence 1 0.2 3% 1 2.0 1%
    
    # echo temporary audio file name to transcription queue
    echo "$tmp"
done > "$audio_fifo" &

# run audio transciption handler
trans