#!/bin/bash

# function to process audio into keystrokes
trans(){
    # Transcribe text
    whisper $1 --language English --model small --output_dir /tmp

    # Type text to terminal
    # Thanks for watching! seems to happen due to noise.
    if [[ $(</tmp/tmp.txt) != "Thanks for watching!" ]]; then
        xdotool type --clearmodifiers --file /tmp/tmp.txt
        xdotool key space
    fi
    # remove temporary file
    rm $1
}

# start doing it
while true; do

# Make another temporary file to hold audio
tmp=$(mktemp)

# Listen to mic. The `&` lets it operate in the background.
# The `1 0.2 3%` part of the sox rec command trims 1 segment of silence from
# the beginning longer than 0.2 seconds and longer than 3% of the volume level.
# The final `1 2.0 1%` part tells it to trim 1 segment of silence from the end.
# It stops recording after 2.0 seconds of silence. Change to 5% or more with
# poor recording equipment and noisy environments.

rec -c 1 -r 22050 -t mp3 $tmp silence 1 0.2 3% 1 2.0 1%

# call our function
trans $tmp&

done
